//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zavrsni_Rad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectures
    {
        public int LecturesID { get; set; }
        public int LecturerID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime LectureDate { get; set; }
        public System.TimeSpan LectureStart { get; set; }
        public System.TimeSpan LectureEnd { get; set; }
        public string LectureText { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual LecturerPerson LecturerPerson { get; set; }
    }
}
